sudo: false
language: ruby
cache: bundler
matrix:
  include:
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=master
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=7.x
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.7
  - rvm: jruby-1.7.27
    env: LOGSTASH_BRANCH=5.6
  fast_finish: true
install: true
script: ci/build.sh
jdk: openjdk8
env:
  matrix:
    secure: juodRMVA90HJEyXOC1JD22DgyZHF4osZGzCzC265Lg0iDW7kLh8jmi2TDcEAjjyP8v5jELDl6G0GZAka0vVeN1qIXRvaIxYExnfzHRG+jb6PUJBobFLvThXvWuSIUOYolO59kc1XfZcJaH4AvxLN7vDWcZ7Ua5Wj1W1zLU0X6H/KOzPGXepWfmVKtbVNWs1ftNA7bQBWXKmzc4ZX3KGUzn48FopmhA7XVxRs9nyB3w0l9CvGQl25J/qf2egr/c7qCTfzPud8h9pVqsoKw9QvPCK9CinfmxIRLn2H1B16hW4RLvcBGA0KOOlpxYGo1JQCekBOzjbZ9maHJ3ZQx4qYOEWIUhPdX0n1K02xX5zVXC9SlEAw506xFz2uqKOjOsgllUKnqWUYmBiYlY0jZplPiWGsQ9lkVFC0s6qg4p+XnOJDuF0tp5ejGthkrdpxoCMon8H5WQ9YOlJPTLx4DPb4weZGgbfHzKbI7BXARp/UpSXITFn3dNHwaGf1dAmQhMIzg9UPX/849Vq83fUPFezHaFL0015CZz422rdzphkUa7keX2kXxOHTeVYserNDVCvz7vLBwNXiUJhYhyaQF5jKt2buFlB6eechFx7VU4XivYQI/QzFO3Xnv8izxeWqH18mk9uYIQ72ZKIGwc63zm0CK6/93yLj0VpqHB3BVanNNWs=
deploy:
  provider: rubygems
  api_key:
    secure: UFa1MVTXNlfHE6SXGK4EaiufODcMOAquezt7KzhPcrxA+0iKVgNGD6qgE00EZO9IPwSDfwzxXz9pu3vOdIiqhkmJ63oFO2uhsbWCkTcjUuHxwWI2bmmohRZE4MVU3DqibxvBeOo0JjByleIoiyf8kUKAFXSuBWih1eYXQsOOLdlLztbt1+SpCgm+jstdkPqtfNH+5g+N618BExrJCFcU+otWPCoG1rS4PQBWLOeoIsbg/DVMlQZrQ3XxFiPGGZ5/mtAvvVXqy/AEivg9VvpdazGGSwEwGj6X5Iz/4ON9WiURsdHiVvFcWLEghFOEhV/PgYvNfCyHBD7cJ8nYMSJppjXFIlpX21QrlpqB0ERogXaKkYYgIAtpxbIyoLl62I+T/+WeDIWaIXFkDl+/4vH3L7ViugXN1GNDSTcok+RjHXW31yZ9K11T6H8l/9Luq8QIHflr3kO1/7pzdQJAKtw4avat/p4pVMGlc3tvy3sla/9NZrG9Qzma7E7Ormvoqjn4SizezLVuMhLMsu1tlhWsFU8/iNL8ptffAvfODPenziE6coP5VnSVeDZDQp31A8318AOf5OUx1mRC7lFn4lUTEo4AkFgpYIvI5MgVU/dMrwVtY2S2GtVG9dl0mkXk1cmffXhzy+pR8FT8aGp3B8DHQ27dnaGxQvwNgbGi/03G9wI=
  gem: logstash-output-sumologic
  on:
    tags: true
    repo: SumoLogic/logstash-output-sumologic
