---
apiVersion: v1
kind: Namespace
metadata:
  name: sumologic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  namespace: sumologic
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
      }
    }
    output {
      if "metric" in [tags] {
        sumologic {
          url => "${SUMO_URL}"
          fields_as_metrics => true
          compress => true
          compress_encoding => "gzip"
          interval => 10
          pile_max => 1024000
          queue_max => 4096
          sender_max => 100
        }
      } else {
        sumologic {
          url => "${SUMO_URL}"
          format => "%{@json}"
          compress => true
          compress_encoding => "gzip"
          interval => 10
          pile_max => 1024000
          queue_max => 4096
          sender_max => 100
        }
      }
      stdout { codec => rubydebug }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: sumologic
spec:
  # replicas: 3
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: sumologic/logstash-output-sumologic:latest
        name: logstash
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        env:
        - name: SUMO_URL
          valueFrom:
            secretKeyRef:
              name: sumologic
              key: sumo-url
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        resources:
          limits:
            memory: 2Gi
            cpu: "200m"
          requests:
            memory: 2Gi
            cpu: "200m"
      volumes:
      - name: pipeline
        configMap:
          name: logstash
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash
          items:
          - key: logstash.yml
            path: logstash.yml
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: sumologic
  labels:
    app: logstash
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP
---
