name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t logstash-output-sumologic .

    - name: Run tests
      run: docker run --rm logstash-output-sumologic
